# Generated by Django 6.0.8 on 2026-08-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='events/banners/'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminar'), ('HACKATHON', 'Hackathon'), ('CONCERT', 'Concert'), ('CONFERENCE', 'Conference'), ('SPORTS', 'Sports'), ('FESTIVAL', 'Festival'), ('COMPETITION', 'Competition'), ('MEETUP', 'Meetup'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags, e.g. python,django,beginner', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, help_text='Specific venue name, e.g. Hall A, TU Campus', max_length=255),
        ),
    ]
