# Generated by Django 6.0.7 on 2026-08-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('PROMOTED', 'Promoted'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20),
        ),
    ]
